services:
  - type: web
    name: youtube-audio-player
    env: docker
    dockerfilePath: ./Dockerfile
    plan: starter # Choose appropriate plan based on your needs
    region: Singapore # Choose region closest to India for better performance
    numInstances: 1
    healthCheckPath: /
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: SESSION_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: youtube-audio-db
          property: connectionString
      # Optional: If your VPN config requires separate credentials
      - key: VPN_USERNAME
        sync: false # Set to true to sync across environments
      - key: VPN_PASSWORD
        sync: false
    disk:
      name: vpn-config
      mountPath: /etc/openvpn
      sizeGB: 1

databases:
  - name: youtube-audio-db
    plan: starter
    region: Singapore # Same region as the web service